version: 2.1

description: Tasks for managing NPM modules in CircleCI builds using Yarn

display:
  home_url: "https://github.com/boxt/orbs"
  source_url: "https://github.com/boxt/yarn-orb/blob/main/config.yml"

commands:
  cache-read:
    parameters:
      version:
        description: Version of the cache to restore
        type: string
        default: "v1"
    steps:
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - yarn-cache-<< parameters.version >>-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-cache-<< parameters.version >>-{{ .Branch }}-
            - yarn-cache-<< parameters.version >>-
          name: Restore yarn cache

  cache-write:
    parameters:
      version:
        description: Version of the cache to save
        type: string
        default: "v1"
    steps:
      - save_cache:
          key: yarn-cache-<< parameters.version >>-{{ .Branch }}-{{checksum "yarn.lock" }}
          name: Save yarn cache
          paths:
            - ~/.cache/yarn
            - ./node_modules

  install:
    steps:
      - run: "yarn install --frozen-lockfile"
